spring.application.name=JamJudge
spring.datasource.url=jdbc:mysql://localhost:3306/jamjudge
spring.datasource.username=root
spring.datasource.password=Fushiguro12!
spring.jpa.hibernate.ddl-auto=update
